name: Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  setup:
    if: github.event.base_ref == 'refs/heads/master'
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Get version
        id: get_version
        run: echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

  create-release:
    name: Create release
    needs:
      - setup
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.setup.outputs.VERSION }}
          name: Aufseher ${{ needs.setup.outputs.VERSION }}
          draft: false
          prerelease: false

  container:
    name: Build and upload container
    needs:
      - setup
      - create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push the Docker image
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: Dockerfile
          image: aufseher
          tags: latest, ${{ needs.setup.outputs.VERSION }}
